# Example configuration for labgrid-fcefyn
# Full exporter config: ansible/files/exporter/labgrid-fcefyn/exporter-isolated.yaml

labgrid-fcefyn-belkin_rt3200_1:
  location: fcefyn-testbed
  RawSerialPort:
    port: "/dev/belkin-rt3200-1"
    speed: 115200
  PDUDaemonPort:
    host: localhost:16421
    pdu: fcefyn-arduino
    index: 0
  TFTPProvider:
    internal: "/srv/tftp/belkin_rt3200_1/"
    external: "belkin_rt3200_1/"
    external_ip: "192.168.100.1"
  NetworkService:
    address: "192.168.1.1%vlan100"
    username: "root"

labgrid-fcefyn-openwrt_one:
  location: fcefyn-testbed
  RawSerialPort:
    port: "/dev/openwrt-one"
    speed: 115200
  PDUDaemonPort:
    host: localhost:16421
    pdu: fcefyn-poe
    index: 1
  TFTPProvider:
    internal: "/srv/tftp/openwrt_one/"
    external: "openwrt_one/"
    external_ip: "192.168.104.1"
  NetworkService:
    address: "192.168.1.1%vlan104"
    username: "root"
