network:
  version: 2
  renderer: NetworkManager
  ethernets:
    enp0s25:
      addresses:
        - 192.168.0.10/24
      dhcp4: true
  vlans:
    vlan200:
      id: 200
      link: enp0s25
      addresses:
        - 192.168.200.1/24
        - 10.13.0.200/16
