all:
  children:
    labs:
      hosts:
        labgrid-aparcar:
          wireguard_ip: 10.0.0.2
          wireguard_pubkey: Y6pZtDrISRhM0+YB+AYg7lcbEDpsazh+egELeaVfnCs=
        labgrid-bastian:
          wireguard_ip: 10.0.0.3
          wireguard_pubkey: YcJbM/wODx9tIhjP446gu5EPlTwXNglWv0I3RfPq+Hc=
        labgrid-blocktrron:
          wireguard_ip: 10.0.0.4
          wireguard_pubkey: P5MgfPEnXarj4CrHV/wCl7l7/v71H5Gp/Dn9B2Dq1DI=
        labgrid-leinelab:
          wireguard_ip: 10.0.0.5
          wireguard_pubkey: W86NNltyBcJLzkaxbeV9S829ynj/Z/kkEN8rG4XOW0s=
        labgrid-hsn:
          wireguard_ip: 10.0.0.7
          wireguard_pubkey: GuOj6TtfUHsdx9HPc+tQaQgd0kD9kWFgieVa7uRu434=
        labgrid-wigyori:
          wireguard_ip: 10.0.0.8
          wireguard_pubkey: YtlFZ4b8bu5jl4sk0NG3QmvQ3Xwa5qBXWlyzpfmWtRs=
        labgrid-hauke:
          wireguard_ip: 10.0.0.9
          wireguard_pubkey: 2fbnODQol0v9mvaL9ksfCDEztgs6MaCwrffYLs5FACI=
        labgrid-fcefyn:
          wireguard_ip: 10.0.0.10
          wireguard_pubkey: lJmI031cyJyi+j9XJCz/oRNMQyVW0sWDL3bEjRXQjls=
        labgrid-bryan:
          wireguard_ip: 10.0.0.11
          wireguard_pubkey: oaxGuWDeNTrae8CUTcW+hv870MtuppKx+qnTOsOkmXg=
    coordinator:
      hosts:
        global-coordinator:
